name: Linux

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  lint:
    if: inputs.version == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: zig/zig build lint
    env:
      SOURCE_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
